### ISSUE TITLE
java.lang.UnsatisfiedLinkError on jvm Target on windows. Works well on JS and jvm mac

### ISSUE THREAD

**Issue by emign** [korlibs/korge#103]
Works on: mac JVM, windows JS, mac JS
Crashes on: windows JVM

Steps to reproduce:
Clone repo and run: https://github.com/emign/unsatiLink

I had to downgrade the wrapper to 5.6.4, because 6.0+ does not work for me (removes dependencies)

```java.lang.UnsatisfiedLinkError: Error looking up function 'glGenBuffers': Die angegebene Prozedur wurde nicht gefunden.

	at com.sun.jna.Function.<init>(Function.java:252)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:594)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:570)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:521)
	at com.soywiz.korgw.win32.Win32GL$Companion$OpenglLoadProxy$1.invoke(Win32GameWindow.kt:52)
	at com.sun.proxy.$Proxy0.glGenBuffers(Unknown Source)
	at com.soywiz.korgw.win32.Win32GL$Companion.glGenBuffers(Win32GameWindow.kt)
	at com.soywiz.korgw.platform.NativeKgl.genBuffers(NativeKgl.kt:62)
	at com.soywiz.korag.AGOpengl$GlBuffer.getGlId(OpenglAG.kt:547)
	at com.soywiz.korag.AGOpengl$GlBuffer.bind(OpenglAG.kt:565)
	at com.soywiz.korag.AGOpengl.draw(OpenglAG.kt:190)
	at com.soywiz.korag.AG.draw(AG.kt:509)
	at com.soywiz.korag.AG.draw$default(AG.kt:508)
	at com.soywiz.korge.render.BatchBuilder2D.flush(BatchBuilder2D.kt:518)
	at com.soywiz.korge.render.RenderContext2D.scissorStart(RenderContext2D.kt:176)
	at com.soywiz.korge.view.Stage.renderInternal(Stage.kt:41)
	at com.soywiz.korge.view.View.render(View.kt:648)
	at com.soywiz.korge.view.Views.render(Views.kt:196)
	at com.soywiz.korge.view.Views.frameUpdateAndRender-_rozLdE(Views.kt:223)
	at com.soywiz.korge.Korge$prepareViews$21.invoke(Korge.kt:382)
	at com.soywiz.korge.Korge$prepareViews$21.invoke(Korge.kt:34)
	at com.soywiz.korev.EventDispatcher$Mixin.dispatch(EventDispatcher.kt:50)
	at com.soywiz.korgw.GameWindow.dispatchRenderEvent(GameWindow.kt:369)
	at com.soywiz.korgw.GameWindow.frame(GameWindow.kt:194)
	at com.soywiz.korgw.win32.Win32GameWindow$windProc$1.callback(Win32GameWindow.kt:316)
	at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:520)
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:551)
	at com.sun.jna.Native.invokeLong(Native Method)
	at com.sun.jna.Function.invoke(Function.java:428)
	at com.sun.jna.Function.invoke(Function.java:361)
	at com.sun.jna.Library$Handler.invoke(Library.java:265)
	at com.sun.proxy.$Proxy2.DispatchMessage(Unknown Source)
	at com.soywiz.korgw.win32.MyUser32$Companion.DispatchMessage(Win32.kt)
	at com.soywiz.korgw.win32.Win32.DispatchMessage(Win32.kt)
	at com.soywiz.korgw.win32.Win32GameWindow.loop(Win32GameWindow.kt:497)
	at com.soywiz.korge.Korge.KoruiWithLogger(Korge.kt:412)
	at com.soywiz.korge.Korge.invoke(Korge.kt:476)
	at me.emig.engineEmi.Engine.start(Engine.kt:52)
	at MainKt.main(Main.kt:48)
	at MainKt$$$main.invoke(Unknown Source)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:199)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:114)
	at kotlin.coroutines.jvm.internal.RunSuspendKt.runSuspend(RunSuspend.kt:19)
	at MainKt.main(Main.kt)
```

**Comment by soywiz** [comment]
Did you solve this?

**Comment by emign** [comment]
fixed
