### ISSUE TITLE
Shader compilation error

### ISSUE THREAD

**Issue by abueide** [korlibs/korge#104]
I get the following error when running :client:runJvm on my desktop with an rx480 on arch linux, but not on my laptop using a really old intel chipset also running arch linux. Only the text doesn't show on the desktop.

I'm using the example project https://github.com/korlibs/korge-samples-client-server

```
> Task :client:runJvm
screenWidth: 4480, screenHeight: 1440, winX=1984, winY=464
VI: native@0x7fb2ec8e9fb0, d: native@0x7fb2ec897b20 (com.sun.jna.platform.unix.X11$Display@ec89fad2), w: 0x7c00001, glc: native@0x7fb2ec8ea4d0
GL_VENDOR: X.Org
GL_VERSION: 4.5 (Compatibility Profile) Mesa 19.3.4
keysim: 0x41
OpenglAG: Created program BatchBuilder2D.Premultiplied.Tinted with id 1 because contextVersion: -1 != 0
java.lang.RuntimeException: Error Compiling Shader : 0 : '0:13(2): error: `gl_FragColor' undeclared
0:13(2): error: value of type vec4 cannot be assigned to variable of type error
0:14(2): error: `gl_FragColor' undeclared
0:14(2): error: type mismatch
0:14(22): error: `gl_FragColor' undeclared
0:14(22): error: type mismatch
0:14(41): error: `gl_FragColor' undeclared
0:14(41): error: type mismatch
0:14(22): error: operands to arithmetic operators must be numeric
0:15(2): error: `gl_FragColor' undeclared
0:15(19): error: `gl_FragColor' undeclared
0:15(19): error: type mismatch
0:15(19): error: operands to arithmetic operators must be numeric
0:15(18): error: operands to arithmetic operators must be numeric
0:16(7): error: `gl_FragColor' undeclared
0:16(7): error: type mismatch
0:16(7): error: operands to relational operators must be scalar and numeric
0:16(7): error: if-statement condition must be scalar boolean
' : source='#version 450
#ifdef GL_ES
	precision mediump float;
	precision mediump int;
	precision lowp sampler2D;
	precision lowp samplerCube;
#endif
uniform sampler2D u_Tex;
varying vec4 v_Col2;
varying vec2 v_Tex;
varying vec4 v_Col;
void main() {
	gl_FragColor = texture2D(u_Tex, v_Tex.xy);
	gl_FragColor.rgb = (gl_FragColor.rgb / gl_FragColor.a);
	gl_FragColor = ((gl_FragColor.rgba * v_Col.rgba) + ((v_Col2.rgba - vec4(0.5, 0.5, 0.5, 0.5)) * 2.0));
	if ((gl_FragColor.a <= 0.0)) {
		discard;
	}
}
', gl.versionInt=450, gl.versionString='4.50', gl=com.soywiz.korgw.x11.X11KmlGl@60129b9a
	at com.soywiz.korag.AGOpengl$GlProgram.createShader(OpenglAG.kt:468)
	at com.soywiz.korag.AGOpengl$GlProgram.ensure(OpenglAG.kt:442)
	at com.soywiz.korag.AGOpengl$GlProgram.use(OpenglAG.kt:474)
	at com.soywiz.korag.AGOpengl.draw(OpenglAG.kt:192)
	at com.soywiz.korag.AG.draw(AG.kt:509)
	at com.soywiz.korag.AG.draw$default(AG.kt:508)
	at com.soywiz.korge.render.BatchBuilder2D.flush(BatchBuilder2D.kt:518)
	at com.soywiz.korge.render.RenderContext2D.scissorEnd(RenderContext2D.kt:200)
	at com.soywiz.korge.view.Stage.renderInternal(Stage.kt:45)
	at com.soywiz.korge.view.View.render(View.kt:648)
	at com.soywiz.korge.view.Views.render(Views.kt:196)
	at com.soywiz.korge.view.Views.frameUpdateAndRender-_rozLdE(Views.kt:223)
	at com.soywiz.korge.Korge$prepareViews$21.invoke(Korge.kt:382)
	at com.soywiz.korge.Korge$prepareViews$21.invoke(Korge.kt:34)
	at com.soywiz.korev.EventDispatcher$Mixin.dispatch(EventDispatcher.kt:50)
	at com.soywiz.korgw.GameWindow.dispatchRenderEvent(GameWindow.kt:369)
	at com.soywiz.korgw.GameWindow.frame(GameWindow.kt:194)
	at com.soywiz.korgw.x11.X11GameWindow$loop$$inlined$apply$lambda$1.invoke(X11GameWindow.kt:188)
	at com.soywiz.korgw.x11.X11GameWindow.loop(X11GameWindow.kt:203)
	at com.soywiz.korge.Korge.KoruiWithLogger(Korge.kt:412)
	at com.soywiz.korge.Korge.invoke-nom0QHw(Korge.kt:437)
	at com.soywiz.korge.Korge.invoke-nom0QHw$default(Korge.kt:435)
	at MainKt.main(main.kt:6)
	at MainKt$$$main.invoke(Unknown Source)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:199)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:114)
	at kotlin.coroutines.jvm.internal.RunSuspendKt.runSuspend(RunSuspend.kt:19)
	at MainKt.main(main.kt
```

**Comment by soywiz** [comment]
Is there a way I can reproduce this in a VM or something? If no, I will need you to try some things locally.

Probably we have to change how glsl is generated and determine when to specify 
https://github.com/korlibs/korgw/blob/96367226f7cba8eb3e2a7184dd26c58381e0e697/korgw/src/commonMain/kotlin/com/soywiz/korag/shader/gl/GlslGenerator.kt#L7

Seems to be related to this:
https://stackoverflow.com/questions/26695253/when-switching-to-glsl-300-met-the-following-error

**Comment by soywiz** [comment]
I have made a potential fix, but I need you to try it first. 

```
git clone https://github.com/korlibs/korgw.git
cd korgw
git checkout fix/not_using_gl_fragColor
sed -i 's/^version=.*/version=1.10.0/g' gradle.properties 
./gradlew publishToMavenLocal
#./gradlew publishJvmPublicationToMavenLocal
```

This should generate the version you are using locally. Then you can try it again and give me the results.

**Comment by abueide** [comment]
@soywiz sorry it took me a while to get back to you on this one.
It seems to fix the error, but it still doesn't render the text.

**Comment by soywiz** [comment]
@abueide thanks! I will investigate further. Probably I will need ti specify the new register somewhere. I will come back to you again for a next try later
