### ISSUE TITLE
MacOS registering gesture listener fails

### ISSUE THREAD

**Issue by Kotlin-Native** [korlibs/korge#1074]
After upgrading from 3.1 to 3.3 I get an error when running jvm target on Mac OS 12.6 (Intel). Java Version 17.0.2.

```
MacOS registering gesture listener...
 -- GestureUtilities=class com.apple.eawt.event.GestureUtilities
Exception in thread "main" java.lang.reflect.InaccessibleObjectException: Unable to make public static void com.apple.eawt.event.GestureUtilities.addGestureListenerTo(javax.swing.JComponent,com.apple.eawt.event.GestureListener) accessible: module java.desktop does not "exports com.apple.eawt.event" to unnamed module @79ab39c4
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at com.soywiz.korgw.internal.MicroDynamic.invoke(MicroDynamic.kt:23)
	at com.soywiz.korgw.awt.BaseAwtGameWindow.loop$suspendImpl(BaseAwtGameWindow.kt:696)
	at com.soywiz.korgw.awt.BaseAwtGameWindow.loop(BaseAwtGameWindow.kt)
	at com.soywiz.korge.Korge.invoke-gBCKsaU(Korge.kt:183)
	at com.soywiz.korge.Korge$invoke$3.invokeSuspend(Korge.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:283)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith$default(DispatchedContinuation.kt:278)
	at kotlinx.coroutines.DispatchedCoroutine.afterResume(Builders.common.kt:260)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by ygdrasil-io** [comment]
Same issue, this can be reproduce just by switching to the 3.3 on the hello world sample.

**Comment by fratima** [comment]
Same issue, for simple korge project.
With
java 17.0.5 2022-10-18
MacOS 13.2.1 Ventura

00:03:10: Executing 'runJvm'...

> Task :compileKotlinJvm UP-TO-DATE
> Task :jvmProcessResources UP-TO-DATE
> Task :jvmMainClasses UP-TO-DATE

> Task :korgeProcessedResourcesJvmMain
Execution optimizations have been disabled for task ':korgeProcessedResourcesJvmMain' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/Users/admin/Programming/Kotlin/myFirstKogre/build/korgeProcessedResources/jvm/main'. Reason: Task ':jvmProcessResources' uses this output of task ':korgeProcessedResourcesJvmMain' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5/userguide/validation_problems.html#implicit_dependency for more details about this problem.

> Task :runJvm
Using DisplayLink
running: Thread[DefaultDispatcher-worker-1,5,main], fvsync=false
MacOS registering gesture listener...
 -- GestureUtilities=class com.apple.eawt.event.GestureUtilities
#21: COMPUTED REFRESH RATE for sun.awt.CGraphicsDevice@3558f4fe (0)
#21: Korgw.GameWindow.TooManyCallbacks, Too many callbacks to handle in this frame elapsedTime=32ms, availableTime=5ms pending timedTasks=0, tasks=0, processedTimedTasks=0, processedTasks=2
Exception in thread "main" java.lang.reflect.InaccessibleObjectException: Unable to make public static void com.apple.eawt.event.GestureUtilities.addGestureListenerTo(javax.swing.JComponent,com.apple.eawt.event.GestureListener) accessible: module java.desktop does not "exports com.apple.eawt.event" to unnamed module @141c9813
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at com.soywiz.korgw.internal.MicroDynamic.invoke(MicroDynamic.kt:23)
	at com.soywiz.korgw.awt.BaseAwtGameWindow.loop$suspendImpl(BaseAwtGameWindow.kt:696)
	at com.soywiz.korgw.awt.BaseAwtGameWindow.loop(BaseAwtGameWindow.kt)
	at com.soywiz.korge.Korge.invoke-gBCKsaU(Korge.kt:183)
	at com.soywiz.korge.Korge$invoke$3.invokeSuspend(Korge.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:283)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith$default(DispatchedContinuation.kt:278)
	at kotlinx.coroutines.DispatchedCoroutine.afterResume(Builders.common.kt:260)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**Comment by soywiz** [comment]
I believe this was fixed. Can you try with KorGE [4.0.0-alpha-5](https://github.com/korlibs/korge/releases/tag/v4.0.0-alpha-5)?

**Comment by fratima** [comment]
Thanks, now it works fine!

**Comment by fratima** [comment]
Hello Carlos,

Many thanks for your fast reply. The new version worked well (the sample files).

Now I wanted to set up a Kotlin project in Intellij that uses Korge 4.0.0
from local maven (.m2) directory. All files seem to be present in .m2.


But I was not able to set up the build.gradle.kts file right so that
I could import com.soywiz.kotlibs.korge2.* 
in main.kt 

It tried all settings I could find on Mac and Windows. Nothing worked.

Is there a page you can refer to showing all the necessary settings?

Thanks in advance
Frank

**Comment by fratima** [comment]
Thanks a lot everything works fine now on my MacBook!
