### ISSUE TITLE
java.lang.RuntimeException: Error Compiling Shader : 0 : 'ERROR: 0:1: '' : syntax error: #version

### ISSUE THREAD

**Issue by emign** [korlibs/korge#123]
After updating to 1.12.0.2 ( I skipped a few versions )
gradle task from runJVM produces blank window on macOS 10.15.4
AdoptopenJDK 11, JDK11, JDK13

js target keeps working as intended. This happens with every sample from korge-samples repository. The background fillcolor gets rendered though.

```
java.lang.RuntimeException: Error Compiling Shader : 0 : 'ERROR: 0:1: '' : syntax error: #version
' : source='#version 120 compatibility
#ifdef GL_ES
	precision mediump float;
	precision mediump int;
	precision lowp sampler2D;
	precision lowp samplerCube;
#endif
uniform sampler2D u_Tex;
varying vec2 v_Tex;
varying vec4 v_Col;
varying vec4 v_Col2;
void main() {
	gl_FragColor = texture2D(u_Tex, v_Tex.xy);
	gl_FragColor.rgb = (gl_FragColor.rgb / gl_FragColor.a);
	gl_FragColor = ((gl_FragColor.rgba * v_Col.rgba) + ((v_Col2.rgba - vec4(0.5, 0.5, 0.5, 0.5)) * 2.0));
	if ((gl_FragColor.a <= 0.0)) {
		discard;
	}
}
', gl.versionInt=120, gl.versionString='1.20', gl=com.soywiz.korgw.osx.MacKmlGL@23f8bdf7
	at com.soywiz.korag.AGOpengl$GlProgram.createShader(OpenglAG.kt:480)
	at com.soywiz.korag.AGOpengl$GlProgram.ensure(OpenglAG.kt:456)
	at com.soywiz.korag.AGOpengl$GlProgram.use(OpenglAG.kt:486)
	at com.soywiz.korag.AGOpengl.draw(OpenglAG.kt:192)
	at com.soywiz.korag.AG.draw(AG.kt:509)
	at com.soywiz.korag.AG.draw$default(AG.kt:508)
	at com.soywiz.korge.render.BatchBuilder2D.flush(BatchBuilder2D.kt:518)
	at com.soywiz.korge.render.BatchBuilder2D.setStateFast(BatchBuilder2D.kt:247)
	at com.soywiz.korge.render.BatchBuilder2D.setStateFast(BatchBuilder2D.kt:240)
	at com.soywiz.korge.render.BatchBuilder2D.drawVertices(BatchBuilder2D.kt:223)
	at com.soywiz.korge.render.BatchBuilder2D.drawVertices$default(BatchBuilder2D.kt:222)
	at com.soywiz.korge.view.RectBase.renderInternal(RectBase.kt:48)
	at com.soywiz.korge.view.Graphics.renderInternal(Graphics.kt:229)
	at com.soywiz.korge.view.View.render(View.kt:635)
	at com.soywiz.korge.view.Container.renderInternal(Container.kt:201)
	at com.soywiz.korge.view.View.render(View.kt:635)
	at com.soywiz.korge.view.Container.renderInternal(Container.kt:201)
	at com.soywiz.korge.view.View.render(View.kt:635)
	at com.soywiz.korge.view.Container.renderInternal(Container.kt:201)
	at com.soywiz.korge.view.View.render(View.kt:635)
	at com.soywiz.korge.view.Container.renderInternal(Container.kt:201)
	at com.soywiz.korge.view.View.render(View.kt:635)
	at com.soywiz.korge.scene.TransitionView.renderInternal(Transition.kt:40)
	at com.soywiz.korge.view.View.render(View.kt:635)
	at com.soywiz.korge.view.Container.renderInternal(Container.kt:201)
	at com.soywiz.korge.view.View.render(View.kt:635)
	at com.soywiz.korge.view.Container.renderInternal(Container.kt:201)
	at com.soywiz.korge.view.Stage.renderInternal(Stage.kt:23)
	at com.soywiz.korge.view.View.render(View.kt:635)
	at com.soywiz.korge.view.Views.render(Views.kt:203)
	at com.soywiz.korge.view.Views.frameUpdateAndRender-_rozLdE(Views.kt:230)
	at com.soywiz.korge.Korge$prepareViews$21.invoke(Korge.kt:366)
	at com.soywiz.korge.Korge$prepareViews$21.invoke(Korge.kt:34)
	at com.soywiz.korev.EventDispatcher$Mixin.dispatch(EventDispatcher.kt:50)
	at com.soywiz.korgw.GameWindow.dispatchRenderEvent(GameWindow.kt:450)
	at com.soywiz.korgw.GameWindow.frameRender(GameWindow.kt:223)
	at com.soywiz.korgw.GameWindow.frame(GameWindow.kt:215)
	at com.soywiz.korgw.GameWindow.frame$default(GameWindow.kt:214)
	at com.soywiz.korgw.awt.AwtGameWindow$frame$1$paint$2.run(AwtGameWindow.kt:169)
	at java.desktop/sun.java2d.opengl.OGLRenderQueue$QueueFlusher.run(OGLRenderQueue.java:231)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

```
java.lang.RuntimeException: Error Compiling Shader : 0 : 'ERROR: 0:1: '' : syntax error: #version
' : source='#version 120 compatibility
#ifdef GL_ES
	precision mediump float;
	precision mediump int;
	precision lowp sampler2D;
	precision lowp samplerCube;
#endif
uniform sampler2D u_Tex;
varying vec2 v_Tex;
varying vec4 v_Col;
varying vec4 v_Col2;
void main() {
	gl_FragColor = texture2D(u_Tex, v_Tex.xy);
	gl_FragColor = ((gl_FragColor.rgba * v_Col.rgba) + ((v_Col2.rgba - vec4(0.5, 0.5, 0.5, 0.5)) * 2.0));
}
', gl.versionInt=120, gl.versionString='1.20', gl=com.soywiz.korgw.osx.MacKmlGL@390fc861
	at com.soywiz.korag.AGOpengl$GlProgram.createShader(OpenglAG.kt:480)
	at com.soywiz.korag.AGOpengl$GlProgram.ensure(OpenglAG.kt:456)
	at com.soywiz.korag.AGOpengl$GlProgram.use(OpenglAG.kt:486)
	at com.soywiz.korag.AGOpengl.draw(OpenglAG.kt:192)
	at com.soywiz.korag.AG.draw(AG.kt:509)
	at com.soywiz.korag.AG.draw$default(AG.kt:508)
	at com.soywiz.korge.render.BatchBuilder2D.flush(BatchBuilder2D.kt:518)
	at com.soywiz.korge.render.BatchBuilder2D.setStateFast(BatchBuilder2D.kt:247)
	at com.soywiz.korge.render.BatchBuilder2D.setStateFast(BatchBuilder2D.kt:240)
	at com.soywiz.korge.render.BatchBuilder2D.drawVertices(BatchBuilder2D.kt:223)
	at com.soywiz.korge.render.BatchBuilder2D.drawVertices$default(BatchBuilder2D.kt:222)
	at com.soywiz.korge.view.RectBase.renderInternal(RectBase.kt:48)
	at com.soywiz.korge.view.Graphics.renderInternal(Graphics.kt:229)
	at com.soywiz.korge.view.View.render(View.kt:635)
	at com.soywiz.korge.view.Container.renderInternal(Container.kt:201)
	at com.soywiz.korge.view.Stage.renderInternal(Stage.kt:23)
	at com.soywiz.korge.view.View.render(View.kt:635)
	at com.soywiz.korge.view.Views.render(Views.kt:203)
	at com.soywiz.korge.view.Views.frameUpdateAndRender-_rozLdE(Views.kt:230)
	at com.soywiz.korge.Korge$prepareViews$21.invoke(Korge.kt:366)
	at com.soywiz.korge.Korge$prepareViews$21.invoke(Korge.kt:34)
	at com.soywiz.korev.EventDispatcher$Mixin.dispatch(EventDispatcher.kt:50)
	at com.soywiz.korgw.GameWindow.dispatchRenderEvent(GameWindow.kt:450)
	at com.soywiz.korgw.GameWindow.frameRender(GameWindow.kt:223)
	at com.soywiz.korgw.GameWindow.frame(GameWindow.kt:215)
	at com.soywiz.korgw.GameWindow.frame$default(GameWindow.kt:214)
	at com.soywiz.korgw.awt.AwtGameWindow$frame$1$paint$2.run(AwtGameWindow.kt:169)
	at java.desktop/sun.java2d.opengl.OGLRenderQueue$QueueFlusher.run(OGLRenderQueue.java:231)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.RuntimeException: Error Compiling Shader : 1282 : 'ERROR: 0:1: '' : syntax error: #version
' : source='#version 120 compatibility
#ifdef GL_ES
	precision mediump float;
	precision mediump int;
	precision lowp sampler2D;
	precision lowp samplerCube;
#endif
uniform sampler2D u_Tex;
varying vec2 v_Tex;
varying vec4 v_Col;
varying vec4 v_Col2;
void main() {
	gl_FragColor = texture2D(u_Tex, v_Tex.xy);
	gl_FragColor.rgb = (gl_FragColor.rgb / gl_FragColor.a);
	gl_FragColor = ((gl_FragColor.rgba * v_Col.rgba) + ((v_Col2.rgba - vec4(0.5, 0.5, 0.5, 0.5)) * 2.0));
	if ((gl_FragColor.a <= 0.0)) {
		discard;
	}
}
', gl.versionInt=120, gl.versionString='1.20', gl=com.soywiz.korgw.osx.MacKmlGL@390fc861
	at com.soywiz.korag.AGOpengl$GlProgram.createShader(OpenglAG.kt:480)
	at com.soywiz.korag.AGOpengl$GlProgram.ensure(OpenglAG.kt:456)
	at com.soywiz.korag.AGOpengl$GlProgram.use(OpenglAG.kt:486)
	at com.soywiz.korag.AGOpengl.draw(OpenglAG.kt:192)
	at com.soywiz.korag.AG.draw(AG.kt:509)
	at com.soywiz.korag.AG.draw$default(AG.kt:508)
	at com.soywiz.korge.render.BatchBuilder2D.flush(BatchBuilder2D.kt:518)
	at com.soywiz.korge.render.BatchBuilder2D.setStateFast(BatchBuilder2D.kt:247)
	at com.soywiz.korge.render.BatchBuilder2D.setStateFast(BatchBuilder2D.kt:240)
	at com.soywiz.korge.render.BatchBuilder2D.drawVertices(BatchBuilder2D.kt:223)
	at com.soywiz.korge.render.BatchBuilder2D.drawVertices$default(BatchBuilder2D.kt:222)
	at com.soywiz.korge.view.RectBase.renderInternal(RectBase.kt:48)
	at com.soywiz.korge.view.Graphics.renderInternal(Graphics.kt:229)
	at com.soywiz.korge.view.View.render(View.kt:635)
	at com.soywiz.korge.view.Container.renderInternal(Container.kt:201)
	at com.soywiz.korge.view.View.render(View.kt:635)
	at com.soywiz.korge.view.Container.renderInternal(Container.kt:201)
	at com.soywiz.korge.box2d.WorldView.renderInternal(Box2d.kt:103)
	at com.soywiz.korge.view.View.render(View.kt:635)
	at com.soywiz.korge.view.Container.renderInternal(Container.kt:201)
	at com.soywiz.korge.view.Stage.renderInternal(Stage.kt:23)
	at com.soywiz.korge.view.View.render(View.kt:635)
	at com.soywiz.korge.view.Views.render(Views.kt:203)
	at com.soywiz.korge.view.Views.frameUpdateAndRender-_rozLdE(Views.kt:230)
	at com.soywiz.korge.Korge$prepareViews$21.invoke(Korge.kt:366)
	at com.soywiz.korge.Korge$prepareViews$21.invoke(Korge.kt:34)
	at com.soywiz.korev.EventDispatcher$Mixin.dispatch(EventDispatcher.kt:50)
	at com.soywiz.korgw.GameWindow.dispatchRenderEvent(GameWindow.kt:450)
	at com.soywiz.korgw.GameWindow.frameRender(GameWindow.kt:223)
	at com.soywiz.korgw.GameWindow.frame(GameWindow.kt:215)
	at com.soywiz.korgw.GameWindow.frame$default(GameWindow.kt:214)
	at com.soywiz.korgw.awt.AwtGameWindow$frame$1$paint$2.run(AwtGameWindow.kt:169)
	at java.desktop/sun.java2d.opengl.OGLRenderQueue$QueueFlusher.run(OGLRenderQueue.java:231)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by soywiz** [comment]
Fixed
