### ISSUE TITLE
java.lang.NumberFormatException: For input string: "2684354884" on maps

### ISSUE THREAD

**Issue by emign** [korlibs/korge#145]
When trying to load a map with 
`val tiledMap = resourcesVfs["Level.tmx"].readTiledMap()`

Level.tmx was created in tiled.

This repo can reproduce the error, its based on the hello-world-example:

https://github.com/emign/tilemap-error

```
> Task :runJvm
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.soywiz.korgw.internal.MicroDynamic (file:/Users/nicolaiemig/.gradle/caches/modules-2/files-2.1/com.soywiz.korlibs.korgw/korgw-jvm/1.12.6/5d423787eeccc332c98ac26e760b1d5815fc5ae5/korgw-jvm-1.12.6.jar) to method com.apple.eawt.FullScreenUtilities.setWindowCanFullScreen(java.awt.Window,boolean)
WARNING: Please consider reporting this to the maintainers of com.soywiz.korgw.internal.MicroDynamic
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
java.lang.NumberFormatException: For input string: "2684354884"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:68)
	at java.base/java.lang.Integer.parseInt(Integer.java:658)
	at java.base/java.lang.Integer.parseInt(Integer.java:776)
	at com.soywiz.korge.tiled.TiledMapKt.readTiledMapData(TiledMap.kt:271)
	at com.soywiz.korge.tiled.TiledMapKt.readTiledMap-kGK-Vss(TiledMap.kt:354)
	at com.soywiz.korge.tiled.TiledMapKt.readTiledMap-kGK-Vss$default(TiledMap.kt:351)
	at MainKt$main$2.invokeSuspend(main.kt:13)
	at MainKt$main$2.invoke(main.kt)
	at com.soywiz.korge.Korge$invoke$4$6$1.invokeSuspend(Korge.kt:160)
	at com.soywiz.korge.Korge$invoke$4$6$1.invoke(Korge.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:177)
	at com.soywiz.korge.Korge$invoke$4$6.invokeSuspend(Korge.kt:157)
	at com.soywiz.korge.Korge$invoke$4$6.invoke(Korge.kt)
	at com.soywiz.korio.async.AsyncExtKt$_launch$1.invokeSuspend(AsyncExt.kt:39)
	at com.soywiz.korio.async.AsyncExtKt$_launch$1.invoke(AsyncExt.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:111)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:158)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:54)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at com.soywiz.korio.async.AsyncExtKt._launch(AsyncExt.kt:37)
	at com.soywiz.korio.async.AsyncExtKt.launchImmediately(AsyncExt.kt:10)
	at com.soywiz.korge.Korge$invoke$4.invokeSuspend(Korge.kt:156)
	at com.soywiz.korge.Korge$invoke$4.invoke(Korge.kt)
	at com.soywiz.korgw.awt.AwtGameWindow$loop$2.invokeSuspend(AwtGameWindow.kt:290)
	at com.soywiz.korgw.awt.AwtGameWindow$loop$2.invoke(AwtGameWindow.kt)
	at com.soywiz.korio.async.AsyncExtKt$_launch$1.invokeSuspend(AsyncExt.kt:39)
	at com.soywiz.korio.async.AsyncExtKt$_launch$1.invoke(AsyncExt.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:111)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:158)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:54)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at com.soywiz.korio.async.AsyncExtKt._launch(AsyncExt.kt:37)
	at com.soywiz.korio.async.AsyncExtKt.launchImmediately(AsyncExt.kt:10)
	at com.soywiz.korio.async.AsyncExtKt.launchImmediately(AsyncExt.kt:19)
	at com.soywiz.korgw.awt.AwtGameWindow.loop(AwtGameWindow.kt:289)
	at com.soywiz.korge.Korge.invoke-j2LsEZk(Korge.kt:103)
	at com.soywiz.korge.Korge.invoke-j2LsEZk$default(Korge.kt:97)
	at MainKt.main(main.kt:12)
	at MainKt$$$main.invoke(Unknown Source)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:199)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:114)
	at kotlin.coroutines.jvm.internal.RunSuspendKt.runSuspend(RunSuspend.kt:19)
	at MainKt.main(main.kt)
Exception in thread "main" java.lang.NumberFormatException: For input string: "2684354884"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:68)
	at java.base/java.lang.Integer.parseInt(Integer.java:658)
	at java.base/java.lang.Integer.parseInt(Integer.java:776)
	at com.soywiz.korge.tiled.TiledMapKt.readTiledMapData(TiledMap.kt:271)
	at com.soywiz.korge.tiled.TiledMapKt.readTiledMap-kGK-Vss(TiledMap.kt:354)
	at com.soywiz.korge.tiled.TiledMapKt.readTiledMap-kGK-Vss$default(TiledMap.kt:351)
	at MainKt$main$2.invokeSuspend(main.kt:13)
	at MainKt$main$2.invoke(main.kt)
	at com.soywiz.korge.Korge$invoke$4$6$1.invokeSuspend(Korge.kt:160)
	at com.soywiz.korge.Korge$invoke$4$6$1.invoke(Korge.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:177)
	at com.soywiz.korge.Korge$invoke$4$6.invokeSuspend(Korge.kt:157)
	at com.soywiz.korge.Korge$invoke$4$6.invoke(Korge.kt)
	at com.soywiz.korio.async.AsyncExtKt$_launch$1.invokeSuspend(AsyncExt.kt:39)
	at com.soywiz.korio.async.AsyncExtKt$_launch$1.invoke(AsyncExt.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:111)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:158)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:54)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at com.soywiz.korio.async.AsyncExtKt._launch(AsyncExt.kt:37)
	at com.soywiz.korio.async.AsyncExtKt.launchImmediately(AsyncExt.kt:10)
	at com.soywiz.korge.Korge$invoke$4.invokeSuspend(Korge.kt:156)
	at com.soywiz.korge.Korge$invoke$4.invoke(Korge.kt)
	at com.soywiz.korgw.awt.AwtGameWindow$loop$2.invokeSuspend(AwtGameWindow.kt:290)
	at com.soywiz.korgw.awt.AwtGameWindow$loop$2.invoke(AwtGameWindow.kt)
	at com.soywiz.korio.async.AsyncExtKt$_launch$1.invokeSuspend(AsyncExt.kt:39)
	at com.soywiz.korio.async.AsyncExtKt$_launch$1.invoke(AsyncExt.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:111)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:158)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:54)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at com.soywiz.korio.async.AsyncExtKt._launch(AsyncExt.kt:37)
	at com.soywiz.korio.async.AsyncExtKt.launchImmediately(AsyncExt.kt:10)
	at com.soywiz.korio.async.AsyncExtKt.launchImmediately(AsyncExt.kt:19)
	at com.soywiz.korgw.awt.AwtGameWindow.loop(AwtGameWindow.kt:289)
	at com.soywiz.korge.Korge.invoke-j2LsEZk(Korge.kt:103)
	at com.soywiz.korge.Korge.invoke-j2LsEZk$default(Korge.kt:97)
	at MainKt.main(main.kt:12)
	at MainKt$$$main.invoke(Unknown Source)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:199)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:114)
	at kotlin.coroutines.jvm.internal.RunSuspendKt.runSuspend(RunSuspend.kt:19)
	at MainKt.main(main.kt)
```

**Comment by soywiz** [comment]
Probably an unsigned integer tried to be parsed as a signed integer

**Comment by RezMike** [comment]
Yeah, current tilemap parsing doesn't support unsigned int values in tilemap. I had the same error when I tried to edit a tilemap in korge-intellij-plugin.
