### ISSUE TITLE
Game fails to start when a second LWJGL App is running

### ISSUE THREAD

**Issue by TobseF** [korlibs/korge#16]
I can't start my [HitKlackOnKorGE](https://github.com/TobseF/HitKlackOnKorGE) as `runJVM` when another LWJGL app is running. Then the korge game fails during start. It's not a big deal for me. And maybe it's a know limitation.

To reproduce you can start [HitKlack](https://github.com/TobseF/HitKlack) as LWJGL Desktop and then, try to run [HitKlackOnKorGE](https://github.com/TobseF/HitKlackOnKorGE) for the jvm.

**Stacktrace:**
```
kotlin.UninitializedPropertyAccessException: lateinit property gl has not been initialized
	at com.soywiz.korag.AGAwtBase.getGl(GLExt.kt:42)
	at com.soywiz.korag.AGOpengl$GlBuffer.<init>(OpenglAG.kt:468)
	at com.soywiz.korag.AGOpengl.createBuffer(OpenglAG.kt:24)
	at com.soywiz.korag.AG.createVertexBuffer(AG.kt:403)
	at com.soywiz.korge.render.BatchBuilder2D.<init>(BatchBuilder2D.kt:42)
	at com.soywiz.korge.render.BatchBuilder2D.<init>(BatchBuilder2D.kt:15)
	at com.soywiz.korge.render.RenderContext.<init>(RenderContext.kt:18)
	at com.soywiz.korge.view.Views.<init>(Views.kt:61)
	at com.soywiz.korge.Korge$invoke$2.invokeSuspend(Korge.kt:414)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
	at com.soywiz.korgw.GameWindowCoroutineDispatcher.executePending(GameWindow.kt:83)
	at com.soywiz.korgw.DefaultGameWindowJvmKt$DefaultGameWindow$1.loop(DefaultGameWindowJvm.kt:379)
	at com.soywiz.korgw.DefaultGameWindowJvmKt$DefaultGameWindow$1$loop$1.invokeSuspend(DefaultGameWindowJvm.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedKt.resumeCancellable(Dispatched.kt:185)
	at kotlinx.coroutines.ResumeModeKt.resumeMode(ResumeMode.kt:22)
	at kotlinx.coroutines.DispatchedKt.resume(Dispatched.kt:272)
	at kotlinx.coroutines.DispatchedKt.dispatch(Dispatched.kt:261)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:218)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:227)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:299)
	at kotlinx.coroutines.EventLoopImplBase$DelayedResumeTask.run(EventLoop.kt:298)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.kt:116)
	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:68)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "kotlinx.coroutines.DefaultExecutor" kotlin.UninitializedPropertyAccessException: lateinit property gl has not been initialized
	at com.soywiz.korag.AGAwtBase.getGl(GLExt.kt:42)
	at com.soywiz.korag.AGOpengl$GlBuffer.<init>(OpenglAG.kt:468)
	at com.soywiz.korag.AGOpengl.createBuffer(OpenglAG.kt:24)
	at com.soywiz.korag.AG.createVertexBuffer(AG.kt:403)
	at com.soywiz.korge.render.BatchBuilder2D.<init>(BatchBuilder2D.kt:42)
	at com.soywiz.korge.render.BatchBuilder2D.<init>(BatchBuilder2D.kt:15)
	at com.soywiz.korge.render.RenderContext.<init>(RenderContext.kt:18)
	at com.soywiz.korge.view.Views.<init>(Views.kt:61)
	at com.soywiz.korge.Korge$invoke$2.invokeSuspend(Korge.kt:414)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
	at com.soywiz.korgw.GameWindowCoroutineDispatcher.executePending(GameWindow.kt:83)
	at com.soywiz.korgw.DefaultGameWindowJvmKt$DefaultGameWindow$1.loop(DefaultGameWindowJvm.kt:379)
	at com.soywiz.korgw.DefaultGameWindowJvmKt$DefaultGameWindow$1$loop$1.invokeSuspend(DefaultGameWindowJvm.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedKt.resumeCancellable(Dispatched.kt:185)
	at kotlinx.coroutines.ResumeModeKt.resumeMode(ResumeMode.kt:22)
	at kotlinx.coroutines.DispatchedKt.resume(Dispatched.kt:272)
	at kotlinx.coroutines.DispatchedKt.dispatch(Dispatched.kt:261)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:218)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:227)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:299)
	at kotlinx.coroutines.EventLoopImplBase$DelayedResumeTask.run(EventLoop.kt:298)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.kt:116)
	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:68)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by TobseF** [comment]
It also fails when I start another Korge engine based jvm desktop app. So to reproduce simply try to run the helllo world template in a seconds instance.

**Comment by soywiz** [comment]
Uhm. That's strange. I didn't know about this issue. I will investigate it this weekend.

**Comment by soywiz** [comment]
I'm trying to reproduce this without luck on a macOS and Windows. Which OS are you using?

**Comment by TobseF** [comment]
Windows 10 x64, DE, Java 1.8.0_201 x64

**Comment by soywiz** [comment]
Shouldn't happen with Korge 1.4.2. Please feel free to reopen if the issue still persists.
