### ISSUE TITLE
KorIO: VfsFile.mkdir() gets java.lang.UnsupportedOperationException: unsupported

### ISSUE THREAD

**Issue by rebokdev** [korlibs/korge#1694]
I tried to use mkdir() on VfsFile and i got:

Exception in thread "DefaultDispatcher-worker-2" java.lang.UnsupportedOperationException: unsupported
	at com.soywiz.korio.lang.ExceptionsKt.unsupported(Exceptions.kt:45)
	at com.soywiz.korio.lang.ExceptionsKt.unsupported$default(Exceptions.kt:45)
	at com.soywiz.korio.file.Vfs.mkdir$suspendImpl(Vfs.kt:188)
	at com.soywiz.korio.file.Vfs.mkdir(Vfs.kt)
	at com.soywiz.korio.file.VfsFile.mkdir(VfsFile.kt:121)
	at com.soywiz.korio.file.VfsFile.mkdir(VfsFile.kt:122)
	at com.soywiz.korio.file.Vfs$Proxy.mkdir$suspendImpl(Vfs.kt:274)
	at com.soywiz.korio.file.Vfs$Proxy.mkdir(Vfs.kt)
	at com.soywiz.korio.file.VfsFile.mkdir(VfsFile.kt:121)
	at com.soywiz.korio.file.VfsFile.mkdir(VfsFile.kt:122)
	at com.soywiz.korio.file.Vfs$Proxy.mkdir$suspendImpl(Vfs.kt:274)
	at com.soywiz.korio.file.Vfs$Proxy.mkdir(Vfs.kt)
	at com.soywiz.korio.file.VfsFile.mkdir(VfsFile.kt:121)
	at com.soywiz.korio.file.VfsFile.mkdir(VfsFile.kt:122)
	at Fenix$1.invokeSuspend(Main.kt:28)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:780)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:684)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:671)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@7dbf195, Dispatchers.Default]

The code was compiled to JVM
kotlin version is 1.8.20
korio vrsion is 4.0.0-alpha-6

**Comment by soywiz** [comment]
Hey @rebokdev can you try with korio `4.0.5` just in case it was fixed already?
BTW: Why are you using `4.0.0-alpha-6` version? Is it referenced somewhere? Or it is a project you started when alpha-6 was out?

And: can you provide an example snippet reproducing the issue? Since VfsFile is generic, it might be referencing to a file reference where it is not possible to create a directory. For example: `resourcesVfs` might be readonly or a mixed set of folders where it is not possible to determine where to create the folder. While `currentLocalVfs` might support it.

**Comment by rebokdev** [comment]
Ok, i solved the problem, i was just trying to mkdir in resources and i didn't know that's not allowed.
