### ISSUE TITLE
Lzma fails on large files

### ISSUE THREAD

**Issue by Martmists-GH** [korlibs/korge#1820]
compressing and uncompressing using Lzma fails unexpectedly with the following snippet:
```kotlin
myBigStringFileContents.encodeToByteArray().compress(Lzma).uncompress(Lzma)
```

With the following error:

```java
java.lang.Exception: Error in data stream
	at korlibs.io.compression.lzma.Lzma.uncompress(Lzma.kt:29)
	at korlibs.io.compression.CompressionMethodKt.uncompress(CompressionMethod.kt:43)
	at korlibs.io.compression.CompressionMethodKt$uncompress$2.invokeSuspend(CompressionMethod.kt:56)
	at korlibs.io.compression.CompressionMethodKt$uncompress$2.invoke(CompressionMethod.kt)
	at korlibs.io.compression.CompressionMethodKt$uncompress$2.invoke(CompressionMethod.kt)
	at korlibs.io.async.RunBlockingNoSuspensionsKt.startCoroutineUndispatched(runBlockingNoSuspensions.kt:73)
	at korlibs.io.async.RunBlockingNoSuspensionsKt.runBlockingNoSuspensions(runBlockingNoSuspensions.kt:40)
	at korlibs.io.compression.CompressionMethodKt.uncompress(CompressionMethod.kt:55)
	at korlibs.io.compression.CompressionMethodKt.uncompress(CompressionMethod.kt:63)
	at korlibs.io.compression.CompressionMethodKt.uncompress$default(CompressionMethod.kt:63)
```

**Comment by ygdrasil-io** [comment]
@Martmists-GH Can you please provide a minimal sample that reproduces the issue?
