### ISSUE TITLE
java.lang.IllegalStateException: Check failed. On loading tilemaps

### ISSUE THREAD

**Issue by emign** [korlibs/korge#192]
> java.lang.IllegalStateException: Check failed.
	at com.soywiz.korge.view.tiles.TileSet$Companion.fromBitmaps(TileSet.kt:73)
	at com.soywiz.korge.tiled.TiledMapKt.readTiledMap-kGK-Vss(TiledMap.kt:384)
	at com.soywiz.korge.tiled.TiledMapKt$readTiledMap$1.invokeSuspend(TiledMap.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at com.soywiz.korgw.GameWindowCoroutineDispatcher.executePending-_v44GIc(GameWindow.kt:104)
	at com.soywiz.korgw.GameWindow.frame-qNqYcK0(GameWindow.kt:261)
	at com.soywiz.korgw.GameWindow.frame-qNqYcK0$default(GameWindow.kt:254)
	at com.soywiz.korgw.awt.AwtGameWindow$frame$1$paint$2.run(AwtGameWindow.kt:170)
	at java.desktop/sun.java2d.opengl.OGLRenderQueue$QueueFlusher.run(OGLRenderQueue.java:231)
	at java.base/java.lang.Thread.run(Thread.java:830)
Exception in thread "Java2D Queue Flusher" java.lang.IllegalStateException: Check failed.
	at com.soywiz.korge.view.tiles.TileSet$Companion.fromBitmaps(TileSet.kt:73)
	at com.soywiz.korge.tiled.TiledMapKt.readTiledMap-kGK-Vss(TiledMap.kt:384)
	at com.soywiz.korge.tiled.TiledMapKt$readTiledMap$1.invokeSuspend(TiledMap.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at com.soywiz.korgw.GameWindowCoroutineDispatcher.executePending-_v44GIc(GameWindow.kt:104)
	at com.soywiz.korgw.GameWindow.frame-qNqYcK0(GameWindow.kt:261)
	at com.soywiz.korgw.GameWindow.frame-qNqYcK0$default(GameWindow.kt:254)
	at com.soywiz.korgw.awt.AwtGameWindow$frame$1$paint$2.run(AwtGameWindow.kt:170)
	at java.desktop/sun.java2d.opengl.OGLRenderQueue$QueueFlusher.run(OGLRenderQueue.java:231)
	at java.base/java.lang.Thread.run(Thread.java:830)

This tilemap: 
[Archiv.zip](https://github.com/korlibs/korge/files/4740855/Archiv.zip)

this code:

```
val tiledMap = resourcesVfs["platformer.tmx"].readTiledMap()
	fixedSizeContainer(256.0, 256.0, clip = true) {
		position(128, 128)
		val camera = camera {
			tiledMapView(tiledMap) {
			}
		}
```

**Comment by emign** [comment]
Another tileset producing this error
[Archiv.zip](https://github.com/korlibs/korge/files/4741485/Archiv.zip)
