### ISSUE TITLE
KorGE plugin crashes constantly

### ISSUE THREAD

**Issue by andres-zym** [korlibs/korge#2230]
I recently found the project and every time I open Intellij Idea I get this message.

com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.soywiz.korge.intellij.actions.KorgeJittoAssistantAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.soywiz.korge.korge-intellij-plugin]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)

IntelliJ Idea 2024.1 Ultimate Edition
macOS Sonoma 14.4.1
Build #IU-241.14494.240, built on March 28, 2024
Runtime version: 17.0.10+8-b1207.12 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

**Comment by soywiz** [comment]
I'm aware of the issue. This will be handled in the coming weeks.

**Comment by soywiz** [comment]
`6.0.0` of the plugin is pending for review.

KorGE Forge is also released that doesn't have this problem: https://blog.korge.org/korge-forge-release
