### ISSUE TITLE
infinite tmx not working

### ISSUE THREAD

**Issue by Kotlin-Native** [korlibs/korge#334]
I've tried to use an infinite tmx file created with Tiled and it crashes if the position of a chunk is in minus.

Korge Version 2.0.5.2

```
<chunk x="0" y="-16" width="16" height="16">
```

```
Exception in thread "Java2D Queue Flusher" java.lang.ArrayIndexOutOfBoundsException: Array index out of range: -256
	at com.soywiz.korge.tiled.TiledMapReaderKt.parseTileLayer(TiledMapReader.kt:394)
	at com.soywiz.korge.tiled.TiledMapReaderKt.readTiledMapData(TiledMapReader.kt:174)
	at com.soywiz.korge.tiled.TiledMapReaderKt.readTiledMap-yw__o68(TiledMapReader.kt:25)
	at com.soywiz.korge.tiled.TiledMapReaderKt.readTiledMap-yw__o68$default(TiledMapReader.kt:22)
	at MainKt$main$2.invokeSuspend(main.kt:38)
	at MainKt$main$2.invoke(main.kt)
	at com.soywiz.korge.Korge$invoke$4$4$1.invokeSuspend(Korge.kt:183)
	at com.soywiz.korge.Korge$invoke$4$4$1.invoke(Korge.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:194)
	at com.soywiz.korge.Korge$invoke$4$4.invokeSuspend(Korge.kt:180)
	at com.soywiz.korge.Korge$invoke$4$4.invoke(Korge.kt)
	at com.soywiz.korio.async.AsyncExtKt$_launch$1.invokeSuspend(AsyncExt.kt:39)
	at com.soywiz.korio.async.AsyncExtKt$_launch$1.invoke(AsyncExt.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:111)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:158)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at com.soywiz.korio.async.AsyncExtKt._launch(AsyncExt.kt:37)
	at com.soywiz.korio.async.AsyncExtKt.launchImmediately(AsyncExt.kt:10)
	at com.soywiz.korge.Korge$invoke$4.invokeSuspend(Korge.kt:179)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.soywiz.korgw.GameWindowCoroutineDispatcher.executePending-_rozLdE(GameWindow.kt:110)
	at com.soywiz.korgw.GameWindow.frameUpdate-_rozLdE(GameWindow.kt:387)
	at com.soywiz.korgw.GameWindow.frame-eeKXlv4(GameWindow.kt:320)
	at com.soywiz.korgw.GameWindow.frame-eeKXlv4$default(GameWindow.kt:317)
	at com.soywiz.korgw.GameWindow.frame(GameWindow.kt:314)
	at com.soywiz.korgw.awt.BaseAwtGameWindow$framePaint$2.invoke(BaseAwtGameWindow.kt:175)
	at com.soywiz.korgw.awt.BaseAwtGameWindow$framePaint$2.invoke(BaseAwtGameWindow.kt:24)
	at com.soywiz.korgw.platform.BaseOpenglContextKt$glContextFromComponent$1$useContext$1.run(BaseOpenglContext.kt:138)
	at sun.java2d.opengl.OGLRenderQueue$QueueFlusher.run(OGLRenderQueue.java:229)
```

**Comment by soywiz** [comment]
Fixed here https://github.com/korlibs/korge/pull/1080
