### ISSUE TITLE
Unsatisfied Link Error with JVM on Apple Silicon

### ISSUE THREAD

**Issue by emign** [korlibs/korge#335]
```
> Task :Lektionen:03.Planetensystem:runJvm FAILED
Exception in thread "main" java.lang.UnsatisfiedLinkError: /Users/USERNAME/Library/Caches/JetBrains/IntelliJIdea2020.3/tmp/jna6890631648374949923.tmp: dlopen(/Users/USERNAME/Library/Caches/JetBrains/IntelliJIdea2020.3/tmp/jna6890631648374949923.tmp, 1): no suitable image found.  Did find:
	/Users/USERNAME/Library/Caches/JetBrains/IntelliJIdea2020.3/tmp/jna6890631648374949923.tmp: no matching architecture in universal wrapper
	/Users/USERNAME/Library/Caches/JetBrains/IntelliJIdea2020.3/tmp/jna6890631648374949923.tmp: no matching architecture in universal wrapper
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1950)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1832)
	at java.lang.Runtime.load0(Runtime.java:811)
	at java.lang.System.load(System.java:1088)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1018)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:988)
	at com.sun.jna.Native.<clinit>(Native.java:195)
	at com.soywiz.korgw.osx.ObjectiveC$Companion.<init>(Cocoa.kt:532)
	at com.soywiz.korgw.osx.ObjectiveC$Companion.<clinit>(Cocoa.kt:83)
	at com.soywiz.korgw.osx.ObjectiveC.<clinit>(Cocoa.kt)
	at com.soywiz.korgw.osx.NSClass.<init>(Cocoa.kt:195)
	at com.soywiz.korgw.osx.NSObject$Companion.<init>(Cocoa.kt:157)
	at com.soywiz.korgw.osx.NSObject$Companion.<init>(Cocoa.kt:157)
	at com.soywiz.korgw.osx.NSObject.<clinit>(Cocoa.kt)
	at com.soywiz.korgw.osx.MacosGameWindowKt.initializeMacOnce(MacosGameWindow.kt:106)
	at com.soywiz.korgw.DefaultGameWindowJvmKt.CreateDefaultGameWindow(DefaultGameWindowJvm.kt:20)
	at com.soywiz.korge.Korge.invoke-7uf206I(Korge.kt:119)
	at com.soywiz.korge.Korge.invoke-7uf206I$default(Korge.kt:113)
	at MainKt.main(main.kt:5)
	at MainKt$$$main.invoke(Unknown Source)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:205)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
	at kotlin.coroutines.jvm.internal.RunSuspendKt.runSuspend(RunSuspend.kt:19)
	at MainKt.main(main.kt)

Execution failed for task ':Lektionen:03.Planetensystem:runJvm'.
> Process 'command '/Users/USERNAME/Library/Java/JavaVirtualMachines/azul-1.8.0_282/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.



```

I use the the Azul 1.8 aarch64 JDK

**Comment by soywiz** [comment]
Related info from JNA:

* https://groups.google.com/g/jna-users/c/RVvk7QcHTFU/m/icw-ncgEBwAJ
* https://github.com/java-native-access/jna/pull/1238
