### ISSUE TITLE
 Can't load library nativewindow_win32.dll

### ISSUE THREAD

**Issue by jihuayu** [korlibs/korge#38]
- When I run the the game with  `./gradlew runJvm` or press the green ▶️ icon , it sometime crash and tell me could't load library.
- I use WIn10 , IDEA , jdk 8/11 and korge-gradle-plugin:1.2.1. 
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: G:\kotlin\korge-hello-world\natives\windows-amd64\\nativewindow_win32.dll
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2620)
	at java.base/java.lang.Runtime.load0(Runtime.java:767)
	at java.base/java.lang.System.load(System.java:1831)
	at com.jogamp.common.jvm.JNILibLoaderBase.loadLibraryInternal(JNILibLoaderBase.java:624)
	at com.jogamp.common.jvm.JNILibLoaderBase.access$000(JNILibLoaderBase.java:63)
	at com.jogamp.common.jvm.JNILibLoaderBase$DefaultAction.loadLibrary(JNILibLoaderBase.java:106)
	at com.jogamp.common.jvm.JNILibLoaderBase.loadLibrary(JNILibLoaderBase.java:487)
	at jogamp.nativewindow.NWJNILibLoader.access$000(NWJNILibLoader.java:39)
	at jogamp.nativewindow.NWJNILibLoader$1.run(NWJNILibLoader.java:49)
	at jogamp.nativewindow.NWJNILibLoader$1.run(NWJNILibLoader.java:41)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at jogamp.nativewindow.NWJNILibLoader.loadNativeWindow(NWJNILibLoader.java:41)
	at jogamp.nativewindow.windows.GDIUtil.initSingleton(GDIUtil.java:60)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.jogamp.common.util.ReflectionUtil.callMethod(ReflectionUtil.java:416)
	at com.jogamp.common.util.ReflectionUtil.callStaticMethod(ReflectionUtil.java:438)
	at com.jogamp.nativewindow.NativeWindowFactory.initSingletonNativeImpl(NativeWindowFactory.java:224)
	at com.jogamp.nativewindow.NativeWindowFactory.initSingleton(NativeWindowFactory.java:388)
	at com.jogamp.opengl.GLProfile.initProfilesForDefaultDevices(GLProfile.java:1721)
	at com.jogamp.opengl.GLProfile.access$000(GLProfile.java:80)
	at com.jogamp.opengl.GLProfile$1.run(GLProfile.java:230)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.jogamp.opengl.GLProfile.initSingleton(GLProfile.java:216)
	at com.jogamp.opengl.GLProfile.getProfileMap(GLProfile.java:2297)
	at com.jogamp.opengl.GLProfile.get(GLProfile.java:988)
	at com.jogamp.opengl.GLProfile.getDefault(GLProfile.java:722)
	at com.jogamp.opengl.GLProfile.getDefault(GLProfile.java:733)
	at com.soywiz.korag.AGAwtBase.<init>(GLExt.kt:35)
	at com.soywiz.korag.AGAwt.<init>(GLExt.kt:67)
	at com.soywiz.korag.AGAwt.<init>(GLExt.kt:67)
	at com.soywiz.korgw.DefaultGameWindowJvmKt$CreateDefaultGameWindow$1$ag$2.invoke(DefaultGameWindowJvm.kt:30)
	at com.soywiz.korgw.DefaultGameWindowJvmKt$CreateDefaultGameWindow$1$ag$2.invoke(DefaultGameWindowJvm.kt:18)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.soywiz.korgw.DefaultGameWindowJvmKt$CreateDefaultGameWindow$1.getAg(DefaultGameWindowJvm.kt)
	at com.soywiz.korgw.DefaultGameWindowJvmKt$CreateDefaultGameWindow$1.<init>(DefaultGameWindowJvm.kt:37)
	at com.soywiz.korgw.DefaultGameWindowJvmKt.CreateDefaultGameWindow(DefaultGameWindowJvm.kt:18)
	at com.soywiz.korge.Korge.KoruiWithLogger(Korge.kt:403)
	at com.soywiz.korge.Korge.invoke(Korge.kt:464)
	at MainKt.main(main.kt:20)
	at MainKt$$$main.invoke(Unknown Source)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:199)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:114)
	at kotlin.coroutines.jvm.internal.RunSuspendKt.runSuspend(RunSuspend.kt:19)
	at MainKt.main(main.kt)

```

**Comment by soywiz** [comment]
Please try again with 1.4.2
