### ISSUE TITLE
JVM target doesn't work on macOS arm64

### ISSUE THREAD

**Issue by IsaacShelton** [korlibs/korge#389]
How to reproduce:

- Open IntelliJ
- New Project -> Korge (using korge version 2.2.1.0)
- Run Gradle Task `runJVM`

`main.kt`:
```
import com.soywiz.klock.seconds
import com.soywiz.korge.*
import com.soywiz.korge.tween.*
import com.soywiz.korge.view.*
import com.soywiz.korim.color.Colors
import com.soywiz.korim.format.*
import com.soywiz.korio.file.std.*
import com.soywiz.korma.geom.degrees
import com.soywiz.korma.interpolation.Easing

suspend fun main() = Korge(width = 512, height = 512, bgcolor = Colors["#2b2b2b"]) {
	val minDegrees = (-16).degrees
	val maxDegrees = (+16).degrees

	val image = image(resourcesVfs["korge.png"].readBitmap()) {
		rotation = maxDegrees
		anchor(.5, .5)
		scale(.8)
		position(256, 256)
	}

	while (true) {
		image.tween(image::rotation[minDegrees], time = 1.seconds, easing = Easing.EASE_IN_OUT)
		image.tween(image::rotation[maxDegrees], time = 1.seconds, easing = Easing.EASE_IN_OUT)
	}
}
```
JVM Stack Trace:
```
Exception in thread "main" java.lang.reflect.InaccessibleObjectException: Unable to make public static void com.apple.eawt.FullScreenUtilities.setWindowCanFullScreen(java.awt.Window,boolean) accessible: module java.desktop does not "exports com.apple.eawt" to unnamed module @40f9161a
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at com.soywiz.korgw.internal.MicroDynamic.invoke(MicroDynamic.kt:23)
	at com.soywiz.korgw.awt.AwtGameWindow$frame$1.<init>(AwtGameWindow.kt:111)
	at com.soywiz.korgw.awt.AwtGameWindow.<init>(AwtGameWindow.kt:48)
	at com.soywiz.korgw.DefaultGameWindowJvmKt.CreateDefaultGameWindow(DefaultGameWindowJvm.kt:43)
	at com.soywiz.korge.Korge.invoke-V4YNAJM(Korge.kt:121)
	at com.soywiz.korge.Korge.invoke-V4YNAJM$default(Korge.kt:91)
	at MainKt.main(main.kt:11)
	at MainKt$main$3.invoke(main.kt)
	at MainKt$main$3.invoke(main.kt)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:205)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
	at kotlin.coroutines.jvm.internal.RunSuspendKt.runSuspend(RunSuspend.kt:19)
	at MainKt.main(main.kt)
```
Java Version:
```
java 16.0.1 2021-04-20
Java(TM) SE Runtime Environment (build 16.0.1+9-24)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)
```

**Comment by IsaacShelton** [comment]
Problem lies in here: https://github.com/korlibs/korge-next/blob/master/korgw/src/jvmMain/kotlin/com/soywiz/korgw/awt/AwtGameWindow.kt

1.
https://github.com/korlibs/korge-next/blob/ef709907f7d16de2bbbbc1aa224a23e8956da96e/korgw/src/jvmMain/kotlin/com/soywiz/korgw/awt/AwtGameWindow.kt#L190-L200

2.
https://github.com/korlibs/korge-next/blob/ef709907f7d16de2bbbbc1aa224a23e8956da96e/korgw/src/jvmMain/kotlin/com/soywiz/korgw/awt/AwtGameWindow.kt#L92-L120

It seems like since JDK9, `com.apple.eawt` isn't accessible anymore. Using regular `GraphicsDevice` would probably solve the problem.

**Comment by soywiz** [comment]
The problem is that

**Comment by soywiz** [comment]
The problem is that setting the frame to the screen bounds doesn't have the same behaviour that real fullscreen on mac.
What I have done is to try to do that, and if it is not possible, then fallback to the common way so at least it doesn't fail.

You can try with:

```
git clone https://github.com/korlibs/korge-next.git
cd korge-next
./gradlew publishJvmLocal
```

Then in your project:

gradle.properties

```
korgePluginVersion=2.0.0.999
...
```

**Comment by IsaacShelton** [comment]
Does https://github.com/korlibs/korge-next/blob/18053baadeb6b9c95bca4587579b8d82ee41b0b5/korgw/src/jvmMain/kotlin/com/soywiz/korgw/awt/AwtGameWindow.kt#L111 need to be wrapped in try-catch as well, or no? The stack trace I got yesterday was thrown from there

I haven't tried the new build yet, but one would think that it would raise the same exception

**Comment by IsaacShelton** [comment]
Pull request that fixes everything: https://github.com/korlibs/korge-next/pull/331
