### ISSUE TITLE
deploy to JVM result in a crash after updating Mac from 11 to 12.0.1

### ISSUE THREAD

**Issue by WarrenFaith** [korlibs/korge#402]
After updating my Mac from Big Sur (OS 11) to Monterey (12.0.1) my super simple app crashes when I try to deploy on jvm. Deploy as native MacOS app works (but takes way longer compared to JVM - minutes instead of seconds).

I am only drawing some circles and lines, so nothing fancy but it seems that getting the display is not working on Monterey anymore.

Following the full output:

```
12:15:11: Executing task 'runJvm'...

> Task :compileKotlinJvm UP-TO-DATE
> Task :jvmProcessResources UP-TO-DATE
> Task :jvmMainClasses UP-TO-DATE
> Task :korgeProcessedResourcesJvmMain

> Task :runJvm
#15: COMPUTED REFRESH RATE for sun.awt.CGraphicsDevice@707d36a0 (60)
WARNING: package sun.awt.X11 not in java.desktop
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.soywiz.korgw.internal.MicroDynamic (file:/Users/..../.gradle/caches/modules-2/files-2.1/com.soywiz.korlibs.korgw/korgw-jvm/2.4.6/4a380dad03c1aa49e711765868b83d4835af181e/korgw-jvm-2.4.6.jar) to method com.apple.eawt.FullScreenUtilities.setWindowCanFullScreen(java.awt.Window,boolean)
WARNING: Please consider reporting this to the maintainers of com.soywiz.korgw.internal.MicroDynamic
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" java.lang.UnsatisfiedLinkError: Error looking up function 'CVDisplayLinkCreateWithCGDisplay': dlsym(0xfff1339e53e0, CVDisplayLinkCreateWithCGDisplay): symbol not found
	at com.sun.jna.Function.<init>(Function.java:252)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:600)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:576)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:562)
	at com.sun.jna.Library$Handler.invoke(Library.java:243)
	at com.sun.proxy.$Proxy2.CVDisplayLinkCreateWithCGDisplay(Unknown Source)
	at com.soywiz.korgw.osx.CoreGraphics$Companion.CVDisplayLinkCreateWithCGDisplay(Cocoa.kt)
	at com.soywiz.korgw.awt.BaseAwtGameWindow.loop$suspendImpl(BaseAwtGameWindow.kt:594)
	at com.soywiz.korgw.awt.BaseAwtGameWindow.loop(BaseAwtGameWindow.kt)
	at com.soywiz.korge.Korge.invoke-DNhgYUs(Korge.kt:126)
	at com.soywiz.korge.Korge.invoke-DNhgYUs$default(Korge.kt:91)
	at MainKt.main(main.kt:11)
	at MainKt$main$3.invoke(main.kt)
	at MainKt$main$3.invoke(main.kt)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:205)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
	at kotlin.coroutines.jvm.internal.RunSuspendKt.runSuspend(RunSuspend.kt:19)
	at MainKt.main(main.kt)
```

Any ideas if there is a workaround?

**Comment by soywiz** [comment]
@WarrenFaith Added your suggestion here: https://github.com/korlibs/docs.korge.org/commit/362a10ec3adb57e5454479ec9f2e39e37796e2b9
Thanks!
