### ISSUE TITLE
Browser builds all crash immediately with Uncaught RangeError

### ISSUE THREAD

**Issue by americanjeff** [korlibs/korge#429]
Easiest repro is runJs from top-level korge-next to run the sandbox.  runJvm produces a working app but runJs produces
```
Uncaught RangeError: byte length of Float32Array should be a multiple of 4
    at new Float32Array (<anonymous>)
    at Fast32BufferF.Fast32Buffer (korge-sandbox.js:101188:25)
    at new Fast32BufferF (korge-sandbox.js:101803:24)
    at NewFast32Buffer (korge-sandbox.js:101485:18)
    at new FBuffer (korge-sandbox.js:99566:28)
    at Companion_2.allocUnaligned_k0bmmj_k$ (korge-sandbox.js:99398:18)
    at init_properties_KmlGlExt_kt_1792131208 (korge-sandbox.js:200794:55)
    at getIntegerv (korge-sandbox.js:200346:11)
    at AGOpengl$createMainRenderBuffer$1.init_ad4727_k$ (korge-sandbox.js:210337:51)
    at korge-sandbox.js:274058:75
```
followed but an unending stream of 
```
korge-sandbox.js:200356 Uncaught TypeError: Cannot read properties of undefined (reading 'setInt_q6h9j0_k$')
    at getIntegerv (korge-sandbox.js:200356:28)
    at AGOpengl$createMainRenderBuffer$1.init_ad4727_k$ (korge-sandbox.js:210337:51)
    at korge-sandbox.js:274058:75
    at BrowserGameWindow.Mixin.dispatch_j8jjro_k$ (korge-sandbox.js:220569:19)
    at doRender (korge-sandbox.js:240699:31)
    at korge-sandbox.js:241805:21
```

**Comment by americanjeff** [comment]
Hmmm, seems to have already been fixed.
