### ISSUE TITLE
When playing a music file the sound is distorted

### ISSUE THREAD

**Issue by jobe-m** [korlibs/korge#497]
When I try to play a mp3 file with Korge 3.0.0-Beta5 the music sounds distorted. I also checked against latest main branch.
To reproduce this I created PR #496.
I can also check if it is reproducible with wave or ogg file formats...
I tested with runjvm on Windows.

**Comment by jobe-m** [comment]
I quickly checked an ogg file and that can even not be played at all. It crashes with:

```
java.lang.IllegalStateException: Can't decode audio stream [[AudioFormat([wav]), NativeMp3DecoderFormat, AudioFormat([ogg]), AudioFormat([])]]
	at com.soywiz.korau.format.AudioFormats.decodeStreamOrError(AudioFormat.kt:118)
	at com.soywiz.korau.sound.NativeSoundProvider.createSound$suspendImpl(Sound.kt:93)
	at com.soywiz.korau.sound.NativeSoundProvider.createSound(Sound.kt)
	at com.soywiz.korau.sound.LazyNativeSoundProvider.createSound$suspendImpl(Sound.kt:47)
	[...]
```

**Comment by jobe-m** [comment]
Awesome, many thanks for fixing it so quickly! I will check it out on my side soon :)

**Comment by jobe-m** [comment]
Music works in my game intro again, yeah!!!
Many, many thanks :)
![kung-fu-master-dance](https://user-images.githubusercontent.com/19785115/176627803-e2e65395-5485-4c13-bb38-d5032f68e523.gif)
