### ISSUE TITLE
java.util.ConcurrentModificationException with rapidly changing shape

### ISSUE THREAD

**Issue by emign** [korlibs/korge#50]
I have a class hierarchy like this:
```
package engineEmi.CanvasElements

import com.soywiz.korim.color.Colors
import com.soywiz.korim.color.RGBA
import com.soywiz.korim.vector.Context2d
import com.soywiz.korma.geom.vector.circle

open class Kreis(
    radius: Number = 10.0,
    x: Number = 100.0,
    y: Number = 100.0,
    fuellFarbe: RGBA = Colors.GREEN,
    randFarbe: RGBA = Colors.RED,
    randDicke: Number = 0.0

) : CanvasElement(x = x.toDouble(), y = y.toDouble()) {

    var radius: Double = radius.toDouble()
        set(value) {
            field = value; updateGraphics()
        }

    var fuellFarbe: RGBA = fuellFarbe
        set(value) {
            field = value; updateGraphics()
        }

    var randFarbe: RGBA = randFarbe
        set(value) {
            field = value; updateGraphics()
        }

    var randDicke: Number = randDicke
        set(value) {
            field = value; updateGraphics()
        }

    init {
        updateGraphics()
    }

    final override fun updateGraphics() {
        graphics.apply {
            clear()
            fillStroke(
                Context2d.Color(fuellFarbe),
                Context2d.Color(randFarbe),
                Context2d.StrokeInfo(thickness = randDicke.toDouble())
            ) {
                circle(x, y, radius)
            }
        }
    }
}

```

```
package engineEmi.CanvasElements

import com.soywiz.korev.MouseEvent
import com.soywiz.korge.view.Container
import com.soywiz.korge.view.sgraphics
import engineEmi.Input.MouseEventReacteable


abstract class CanvasElement(
    x: Double,
    y: Double
) : Container(), MouseEventReacteable {

    init {
        super.x = x
        super.y = y
    }

    val graphics = sgraphics {
    }

    var animationRoutine: () -> Any = {}

    open suspend fun animate() {
        animationRoutine()
    }

    open suspend fun prepareElement() {}

    abstract fun updateGraphics()

    override fun reactToMouseEvent(event: MouseEvent) {}
}

```

When overriding the animate()-function in a subclass of `Kreis` with a rapidly changing property-value (like radius for resizing), it throws a ConcurrentModificationException. Probably because the Container(View) Object has changed due to the new radius in the meantime. 

> java.util.ConcurrentModificationException
> 	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
> 	at java.util.ArrayList$Itr.next(ArrayList.java:859)
> 	at com.soywiz.korim.vector.CompoundShape.draw(Shape.kt:347)
> 	at com.soywiz.korge.view.Graphics.renderInternal(Graphics.kt:217)
> 	at com.soywiz.korge.view.View.render(View.kt:443)
> 	at com.soywiz.korge.view.Container.renderInternal(Container.kt:95)
> 	at com.soywiz.korge.view.View.render(View.kt:443)
> 	at com.soywiz.korge.view.Container.renderInternal(Container.kt:95)
> 	at com.soywiz.korge.view.Stage.renderInternal(Views.kt:306)
> 	at com.soywiz.korge.view.View.render(View.kt:443)
> 	at com.soywiz.korge.view.Views.render(Views.kt:194)
> 	at com.soywiz.korge.view.Views.frameUpdateAndRender-_rozLdE(Views.kt:223)
> 	at com.soywiz.korge.Korge$prepareViews$21.invoke(Korge.kt:374)
> 	at com.soywiz.korge.Korge$prepareViews$21.invoke(Korge.kt:31)
> 	at com.soywiz.korev.EventDispatcher$Mixin.dispatch(EventDispatcher.kt:50)
> 	at com.soywiz.korgw.jogl.JoglGameWindow$loop$2.invoke(JoglGameWindow.kt:700)
> 	at com.soywiz.korgw.jogl.JoglGameWindow$loop$2.invoke(JoglGameWindow.kt:22)
> 	at com.soywiz.korio.async.Signal.invoke(Signal.kt:87)
> 	at com.soywiz.korgw.jogl.AGAwt$glEventListener$1.display(JoglGameWindow.kt:506)
> 	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
> 	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
> 	at com.jogamp.opengl.awt.GLCanvas$11.run(GLCanvas.java:1424)
> 	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
> 	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
> 	at com.jogamp.opengl.awt.GLCanvas$12.run(GLCanvas.java:1438)
> 	at com.jogamp.opengl.Threading.invoke(Threading.java:223)
> 	at com.jogamp.opengl.awt.GLCanvas.display(GLCanvas.java:505)
> 	at com.jogamp.opengl.awt.GLCanvas.paint(GLCanvas.java:559)
> 	at com.jogamp.opengl.awt.GLCanvas.update(GLCanvas.java:866)
> 	at sun.awt.RepaintArea.updateComponent(RepaintArea.java:255)
> 	at sun.lwawt.LWRepaintArea.updateComponent(LWRepaintArea.java:47)
> 	at sun.awt.RepaintArea.paint(RepaintArea.java:232)
> 	at sun.lwawt.LWComponentPeer.handleJavaPaintEvent(LWComponentPeer.java:1314)
> 	at sun.lwawt.LWComponentPeer.handleEvent(LWComponentPeer.java:1198)
> 	at java.awt.Component.dispatchEventImpl(Component.java:4965)
> 	at java.awt.Component.dispatchEvent(Component.java:4711)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
> 	at java.awt.EventQueue.access$500(EventQueue.java:97)
> 	at java.awt.EventQueue$3.run(EventQueue.java:709)
> 	at java.awt.EventQueue$3.run(EventQueue.java:703)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
> 	at java.awt.EventQueue$4.run(EventQueue.java:733)
> 	at java.awt.EventQueue$4.run(EventQueue.java:731)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by emign** [comment]
For me it seems to be fixed.
