### ISSUE TITLE
Android test issues

### ISSUE THREAD

**Issue by soywiz** [korlibs/korge#527]
```
    Caused by: java.lang.RuntimeException: Method getMainLooper in android.os.Looper not mocked. See http://g.co/androidstudio/not-mocked for details.
        at android.os.Looper.getMainLooper(Looper.java)
        at kotlinx.coroutines.android.AndroidDispatcherFactory.createDispatcher(HandlerDispatcher.kt:55)
        at kotlinx.coroutines.android.AndroidDispatcherFactory.createDispatcher(HandlerDispatcher.kt:52)
        at kotlinx.coroutines.internal.MainDispatchersKt.tryCreateDispatcher(MainDispatchers.kt:57)
        at kotlinx.coroutines.internal.MainDispatcherLoader.loadMainDispatcher(MainDispatchers.kt:38)
        at kotlinx.coroutines.internal.MainDispatcherLoader.<clinit>(MainDispatchers.kt:22)
        at kotlinx.coroutines.Dispatchers.getMain(Dispatchers.kt:58)
        at com.soywiz.korio.async.AsyncExtAndroidKt.asyncEntryPoint(AsyncExtAndroid.kt:6)
        at com.soywiz.korio.async.AsyncExtKt.suspendTest-X_cglJY(AsyncExt.kt:30)
        at com.soywiz.korio.async.AsyncExtKt.suspendTest(AsyncExt.kt:32)
        at com.soywiz.korio.async.SleepTest.name(SleepTest.kt:12)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```

**Comment by soywiz-invideo** [comment]
https://github.com/korlibs/korge/issues/407
