### ISSUE TITLE
Android crashes during start in Korge main-VfsList is empty []

### ISSUE THREAD

**Issue by TobseF** [korlibs/korge#81]
My Android build of my WIP candy crush clones crashes during start.   
With `runJvm` the Game runs fine.  
`korgePluginVersion = "1.5.4.0"` 
``` kotlin
suspend fun main() = Korge(width = 1280, height = 1024,
                           bgcolor = Colors["#2b2b2b"], debug = true) {
```
Full SourceCode: [🍭github/candy-crush-clone](https://github.com/TobseF/candy-crush-clone)

😼👓**Logcat**:  
> ⚡`IllegalStateException`-`VfsList is empty []`
``` java
Process: j4k.candycrush, PID: 11708
java.lang.IllegalStateException: MergedVfs.access: VfsList is empty []
	at com.soywiz.korio.file.std.MergedVfs.access$suspendImpl(MergedVfs.kt:26)
	at com.soywiz.korio.file.std.MergedVfs.access(Unknown Source:0)
	at com.soywiz.korio.file.Vfs$Proxy.readRange$suspendImpl(Vfs.kt:158)
	at com.soywiz.korio.file.Vfs$Proxy.readRange(Unknown Source:0)
	at com.soywiz.korio.file.VfsFile.readRangeBytes(VfsFile.kt:69)
	at com.soywiz.korio.file.Vfs$Proxy.readRange$suspendImpl(Vfs.kt:158)
	at com.soywiz.korio.file.Vfs$Proxy.readRange(Unknown Source:0)
	at com.soywiz.korio.file.VfsFile.readRangeBytes(VfsFile.kt:69)
	at com.soywiz.korio.file.Vfs$Proxy.readRange$suspendImpl(Vfs.kt:158)
	at com.soywiz.korio.file.Vfs$Proxy.readRange(Unknown Source:0)
	at com.soywiz.korio.file.VfsFile.readAll(VfsFile.kt:73)
	at com.soywiz.korio.file.VfsFile.read(VfsFile.kt:75)
	at com.soywiz.korim.format.KorioExtKt.readBitmap(KorioExt.kt:106)
	at com.soywiz.korim.format.KorioExtKt.readBitmap$default(KorioExt.kt:98)
	at MainKt$main$2.invokeSuspend(main.kt:24)
	at MainKt$main$2.invoke(Unknown Source:10)
	at com.soywiz.korge.Korge$invoke$2$3.invokeSuspend(Korge.kt:464)
	at com.soywiz.korge.Korge$invoke$2$3.invoke(Unknown Source:10)
	at com.soywiz.korio.async.AsyncExtKt$_launch$1.invokeSuspend(AsyncExt.kt:34)
	at com.soywiz.korio.async.AsyncExtKt$_launch$1.invoke(Unknown Source:10)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:111)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:158)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:54)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
	at com.soywiz.korio.async.AsyncExtKt._launch(AsyncExt.kt:32)
	at com.soywiz.korio.async.AsyncExtKt.launchImmediately(AsyncExt.kt:9)
	at com.soywiz.korge.Korge$invoke$2.invokeSuspend(Korge.kt:463)
	at com.soywiz.korge.Korge$invoke$2.invoke(Unknown Source:10)
	at com.soywiz.korge.Korge$KoruiWithLogger$2.invokeSuspend(Korge.kt:408)
	at com.soywiz.korge.Korge$KoruiWithLogger$2.invoke(Unknown Source:10)
	at com.soywiz.korgw.AndroidGameWindow.loop(DefaultGameWindowAndroid.kt:74)
	at com.soywiz.korge.Korge.KoruiWithLogger(Korge.kt:407)
	at com.soywiz.korge.Korge.invoke-nom0QHw(Korge.kt:432)
	at com.soywiz.korge.Korge.invoke-nom0QHw$default(Korge.kt:430)
	at MainKt.main(main.kt:20)
	at j4k.candycrush.MainActivity.activityMain(MainActivity.kt:13)
	at com.soywiz.korgw.KorgwActivity$onCreate$2$1.invokeSuspend(KorgwActivity.kt:169)
	at com.soywiz.korgw.KorgwActivity$onCreate$2$1.invoke(Unknown Source:10)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:154)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
	at com.soywiz.korgw.KorgwActivity$onCreate$2.invokeSuspend(KorgwActivity.kt:168)
	at com.soywiz.korgw.KorgwActivity$onCreate$2.invoke(Unknown Source:10)
	at com.soywiz.korio.KorioAndroidKt$Korio$1$1.invokeSuspend(KorioAndroid.kt:8)
	at com.soywiz.korio.KorioAndroidKt$Korio$1$1.invoke(Unknown Source:10)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:154)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
	at com.soywiz.korio.android.KorioAndroidContextKt.withAndroidContext(KorioAndroidContext.kt:19)
	at com.soywiz.korio.KorioAndroidKt$Korio$1.invokeSuspend(KorioAndroid.kt:8)
	at com.soywiz.korio.KorioAndroidKt$Korio$1.invoke(Unknown Source:10)
	at com.soywiz.korio.async.AsyncExtAndroidKt$asyncEntryPoint$1.invokeSuspend(AsyncExtAndroid.kt:7)
	at com.soywiz.korio.async.AsyncExtAndroidKt$asyncEntryPoint$1.invoke(Unknown Source:10)
	at com.soywiz.korio.async.AsyncExtKt$_launch$1.invokeSuspend(AsyncExt.kt:34)
	at com.soywiz.korio.async.AsyncExtKt$_launch$1.invoke(Unknown Source:10)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:111)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:158)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:54)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
	at com.soywiz.korio.async.AsyncExtKt._launch(AsyncExt.kt:32)
	at com.soywiz.korio.async.AsyncExtKt.launch(AsyncExt.kt:8)
	at com.soywiz.korio.async.AsyncExtAndroidKt.asyncEntryPoint(AsyncExtAndroid.kt:6)
	at com.soywiz.korio.KorioAndroidKt.Korio(KorioAndroid.kt:8)
	at com.soywiz.korgw.KorgwActivity.onCreate(KorgwActivity.kt:166)
	at android.app.Activity.performCreate(Activity.java:7159)
	at android.app.Activity.performCreate(Activity.java:7150)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3001)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3156)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1864)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:205)
	at android.app.ActivityThread.main(ActivityThread.java:6991)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)
  Force finishing activity j4k.candycrush/.MainActivity

```

**Comment by soywiz** [comment]
Have you tried with 1.5.6.2 that is the latest version?

**Comment by TobseF** [comment]
✔ Ok ... it works on `1.5.6.2`
It's easy to miss a update.

I always check the korge releases on https://github.com/korlibs/korge/releases
There we have the recent release version on `1.5.4.0`. And the newest tag with `release-1.5.6 `
But also on the korge-plugins the recent Release is `1.5.4.0`:
https://github.com/korlibs/korge-plugins/releases

So I have to keep in mind to check the bintray repo:
https://bintray.com/korlibs/korlibs/korge-plugins/view/files/com/soywiz/korge/com.soywiz.korge.gradle.plugin/#files/com/soywiz/korge/com.soywiz.korge.gradle.plugin/
