### ISSUE TITLE
Crash on runJVM while connected to Airplay server

### ISSUE THREAD

**Issue by emign** [korlibs/korge#98]
When connected to airplay and mirroring the screen, `runJVM` produces this crash on mac OS:
It works flawlessly, when NOT being connected to airplay and when NOT mirroring, but using the airplay device as a separate screen.
```
WARNING. Slower startup: NOT in main thread! Using AWT! (on mac use -XstartOnFirstThread when possible)
Korge gameWindow.loop completed
Exception in thread "main" java.lang.NullPointerException
	at java.desktop/java.awt.Window.init(Window.java:509)
	at java.desktop/java.awt.Window.<init>(Window.java:549)
	at java.desktop/java.awt.Frame.<init>(Frame.java:423)
	at java.desktop/javax.swing.JFrame.<init>(JFrame.java:224)
	at com.soywiz.korgw.awt.AwtGameWindow$frame$1.<init>(AwtGameWindow.kt:65)
	at com.soywiz.korgw.awt.AwtGameWindow.<init>(AwtGameWindow.kt:65)
	at com.soywiz.korgw.DefaultGameWindowJvmKt.CreateDefaultGameWindow(DefaultGameWindowJvm.kt:38)
	at com.soywiz.korge.Korge.KoruiWithLogger(Korge.kt:406)
	at com.soywiz.korge.Korge.invoke(Korge.kt:470)
	at me.emig.engineEmi.Engine.start(Engine.kt:52)
	at MainKt.main(Main.kt:47)
	at MainKt$$$main.invoke(Unknown Source)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:199)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:114)
	at kotlin.coroutines.jvm.internal.RunSuspendKt.runSuspend(RunSuspend.kt:19)
	at MainKt.main(Main.kt)
```

**Comment by soywiz** [comment]
Interesting. I will investigate.

**Comment by emign** [comment]
teacher's problems

**Comment by soywiz** [comment]
Happens on both first thread and non-first thread?

**Comment by soywiz** [comment]
![2020-03-10 (2)](https://user-images.githubusercontent.com/570848/76357551-36531180-6318-11ea-9be2-10dbd94565dc.png)

Looks like a Java issue. Not sure if I can do something about that

**Comment by emign** [comment]
Okay... too bad. You still need the info then?

**Comment by soywiz** [comment]
Well I downloaded java 8, java 11 and java 13. The only line that make sense is the one on jdk 13. Have you tried on other jdks, just in case that's a regression? Java 14 is going to be released soon. Also you can create a JFrame and see if that happens too with a simple JFrame, then report it to the java issue tracker.

**Comment by emign** [comment]
I almost always stay on java 11. I will wait for java 14 and see whats happening :)
